version: "3.9"
services:
  my_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
    depends_on:
      - my_db
    # deploy:
    #   restart_policy:
    #     condition: always
    #     delay: 3s


  my_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./mysql.env
    # deploy:
    #   restart_policy:
    #     condition: always  