#@baseUrl = http://localhost:80
@baseUrl = http://ttpang.site/

### 특정 테트로미노 풀 요구
GET {{baseUrl}}/api/tetro/get-tetro/1 HTTP/1.1
Accept: application/json

### 존재하지 않는 테트로미노 풀 요구
GET {{baseUrl}}/api/tetro/get-tetro/10 HTTP/1.1
Accept: application/json

### 특정 테트로미노 풀에 대한 점수 요청
GET {{baseUrl}}/api/tetro/get-scores/1 HTTP/1.1
Accept: application/json


### 특정 점수를 삽입
POST {{baseUrl}}/api/tetro/set-score/1 HTTP/1.1
Content-Type: : application/json

{
    "name": "test",
    "score": 900
}


### 사용 가능한 대학 목록
GET {{baseUrl}}/api/info/univs HTTP/1.1
Accept: application/json


### 사용가능한 테트로미노 풀 목록
GET {{baseUrl}}/api/info/1/tetro-pools HTTP/1.1
Accept: application/json
